import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Inter } from "next/font/google";
import { Flex, Theme } from "@radix-ui/themes";
import Menu from "@/components/Menubar";
import { Providers } from "@/redux/provider";
import Footer from "@/components/Footer";
import Header from "../commons/Header";
import { Toaster } from "sonner";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bodyMain"
        style={{ backgroundColor: "rgb(244, 244, 244)" }}
      >
        <Providers>
          <Theme>
            <Flex justify={"center"} width={"90%"}>
              <header>
                <Menu />
              </header>
            </Flex>
            <Header />
            <Flex justify={"center"} style={{ margin: "2%" }}>
              {children}
              <Toaster position="bottom-center"/>
            </Flex>
          </Theme>
          <div style={{ marginBottom: "100px" }}></div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
