import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Inter } from "next/font/google";
import { Flex, Theme } from "@radix-ui/themes";
import Menu from "@/components/Menubar";
import { Providers } from "@/redux/provider";
import MyFooter from "@/components/MyFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bodyMain">
        <Providers>
          <Theme>
            <Flex justify={"center"} width={"90%"}>
              <header>
                <Menu />
              </header>
            </Flex>
            <Flex justify={"center"} style={{ margin: "2%" }}>
              {children}
            </Flex>
          </Theme>
          <MyFooter />
        </Providers>
      </body>
    </html>
  );
}
