import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Inter } from "next/font/google";
import { Flex, Theme } from "@radix-ui/themes";
import Menu from "@/components/Menubar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme
          accentColor="cyan"
          grayColor="gray"
          panelBackground="solid"
          scaling="100%"
          radius="full"
        >
          <Flex justify={"center"} width={"90%"}>
            <header>
              <Menu />
            </header>
          </Flex>
          <Flex justify={"center"} style={{ marginTop: "2%" }}>
            {children}
          </Flex>
        </Theme>
      </body>
    </html>
  );
}
